name: code-sprint-2022
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - xarray
  - numpy=1.21
  - jupyterlab
  - dask
  - zarr
  - rioxarray
  - fsspec
  - s3fs
  - netCDF4
  - pygeoapi
  - flask_cors
  - jinja2=3.0.3
  - shapely
  - cf_xarray
  - ndpyramid
  - matplotlib
  - httpx
  - git
  - pip
  - hvplot
  - holoviews
  - bokeh
  - pip:
      - git+https://github.com/xarray-contrib/xpublish.git@632a720aadba39cebaf062da7043835262d9fa3d
      - opendap-protocol
  - Pillow
  - rasterio
  - pyproj
  - ipytree
  - xesmf
  - mercantile
