title: "GFS Wave"
description: ""
pangeo_forge_version: "0.8.2"
pangeo_notebook_version: "2021.12.02"
recipes:
  - id: riops
    object: "recipe:recipe"
provenance:
  providers:
    - name: ""
      description: ""
      roles:
        - producer
        - licensor
      url: https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/
  license: "CC-BY-4.0"
maintainers:
  - name: "James Munroe"
    orcid: "0000-0002-4078-0852"
    github: jmunroe
bakery:
  id: "pangeo-ldeo-nsf-earthcube"
